# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='categorias',
            field=models.ManyToManyField(to='polls.Categoria'),
        ),
    ]
